In [1]:
print("Hello World")

Hello World


In [2]:
!pip3 install numpy

# We are going to learn numpy now

#### this is the new headline

In [3]:
import numpy as np

In [13]:
arr = np.array([1, 2, 3])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.ndim

1

In [23]:
arr.shape

(3,)

In [24]:
arr.size

3

In [25]:
arr.dtype

dtype('int32')

In [26]:
a = np.array([[1, 2, 3],[5, 6, 7]], dtype = 'float')
print("Array create using passed list:\n",a)

Array create using passed list:
 [[1. 2. 3.]
 [5. 6. 7.]]


In [28]:
c = np.zeros((3, 4))

In [29]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
f = np.arange(0, 30, 5)
print("\n sequential array with step of 0 to  5:\n",f)

g = np.linspace(0, 5, 10)
print("\n sequential array with 10 values between  0 to  5:\n",g)



 sequential array with step of 0 to  5:
 [ 0  5 10 15 20 25]

 sequential array with 10 values between  0 to  5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [39]:
arr = np.array([[1,2,3,4],
                [5,2,3,2],
                [2,1,0,1]])
newarr = arr.reshape((4,6))

ValueError: cannot reshape array of size 12 into shape (4,6)

In [45]:
arr =np.array([[1,2,0,4],
              [4,0.5,6,0],
              [4,0.5,6,0],
               [1,2,0,4]])
              

In [46]:
arr

array([[1. , 2. , 0. , 4. ],
       [4. , 0.5, 6. , 0. ],
       [4. , 0.5, 6. , 0. ],
       [1. , 2. , 0. , 4. ]])

In [47]:
arr[1::2, :3:2]

array([[4., 6.],
       [1., 0.]])

In [49]:
a = np.array([1,2,4,5,6])

In [50]:
a+1

array([2, 3, 5, 6, 7])